### ISSUE TITLE
Move/Remove files in root directory of repo

### ISSUE THREAD

**Issue by Heenne** [matchRos/Match_Mobile_Robotics#12]
[Jacobi_symbolic.m](https://github.com/matchRos/Match_Mobile_Robotics/blob/noetic-devel/Jacobi_symbolic.m) 
and 
[setup_noetic.sh](https://github.com/matchRos/Match_Mobile_Robotics/blob/noetic-devel/setup_noetic.sh)
should be moved to utilities repository

**Comment by matchRos** [comment]
done
