### ISSUE TITLE
installtion's error when install dependencies

### ISSUE THREAD

**Issue by fuwei-li** [matchRos/Match_Mobile_Robotics#5]
met following error when execute the first command git submodule update --init --recursive
error message:
fatal: No url found for submodule path 'panda/panda_franka_description' in .gitmodules

**Comment by Heenne** [comment]
@fuwei-li 
Should be fixed in latest version of the main branch.
(commit 17a3d024a132873c9b227ea587d8b9e6a048bec9)

Please try it again and report back so we can close this issue, thanks.

**Comment by fuwei-li** [comment]
@Heenne 
The problem get fixed. Thank you!
